module Domainic
  module Dev
    # A command line interface for development tools in the Domainic gem.
    #
    # This class extends Thor to provide CLI commands for development tasks like running tests. Each command inherits
    # from {Command::BaseCommand} and can include mixins from the {Command::Mixin} namespace for common functionality.
    #
    # @author {https://aaronmallen.me Aaron Allen}
    # @since 0.1.0
    class CLI < Thor
      # Whether to exit with a non-zero status on command failure.
      #
      # @return [Boolean] `true` to exit with non-zero status on failure
      def self.exit_on_failure?: () -> bool
    end
  end
end
