default: true

MD007:
  indent: 2

MD013:
  line_length: 120
  tables: false

# Allow CHANGELOG.md like nesting
MD024:
  allow_different_nesting: true

MD029:
  style: ordered

# Allow collapsible details
MD033:
  allowed_elements:
    - details
    - summary
