inherit_from: .rubocop-base.yml

require:
  - rubocop-on-rbs
  - rubocop-ordered_methods
  - rubocop-yard
  - ./domainic-dev/lib/domainic/dev/domainic_cops

RBS:
  Enabled: true

RBS/Lint/AmbiguousOperatorPrecedence:
  Enabled: false # disabling pending the resolution of https://github.com/soutaro/rbs-inline/issues/174
