require:
  - rubocop-on-rbs
  - rubocop-performance
  - rubocop-rspec
  - rubocop-yard

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 3.1

RBS:
  Enabled: true
