class Thor
  def self.at_least_one: () { (self) -> void } -> void

  def self.default_command: (Symbol method) -> void

  def self.desc: (String usage, String description) -> void

  def self.exit_on_failure?: () -> bool

  def self.long_desc: (String long_description, ?wrap: bool) -> void

  def self.option: (Symbol name, Hash[Symbol, untyped] options) -> void

  def self.package_name: (String) -> void

  def self.subcommand: (String command, Class | Module klass) -> void

  def invoke: (String | Symbol command, ?Array[untyped] args, ?Hash[Symbol, untyped] options) -> void

  def options: () -> Hash[Symbol, untyped]

  # I realize this is probably not where this should go but to be fair this is not a signature I should HAVE to write.
  # This signature is here to override the default Kernel#system signature which claims `exception` is a not a valid
  # argument. This is not true, it is a valid argument. This is a hack to get around that. This will likely remain here
  # until the RBS team fixes the issue.
  def system: (::String, *::String, ?exception: ::boolish) -> (bool | nil)
            | (::Hash[::string, (::string | nil)], ::String, *::String, ?exeption: ::boolish) -> (bool | nil)
end
