module Domainic
  module Dev
    class CLI < Thor
      class Lint < Thor
        def all: () -> void

        def markdown: () -> void

        def ruby: (*String options) -> void

        def types: () -> void
      end
    end
  end
end
