module Domainic
  module Dev
    class CLI < Thor
      class Version < Thor
        def bump: (String gem_name) -> void

        def set: (String gem_name) -> void

        def sync: () -> void
      end
    end
  end
end
