module Domainic
  module Type
    # @since 0.1.0
    class AnythingType
      include Behavior

      def but: (*untyped types) -> untyped

      alias except but

      alias excluding but
    end
  end
end
