module Domainic
  module Type
    module Constraint
      # @since 0.1.0
      class AllConstraint
        include Behavior

        @expected: Behavior

        def description: ...

        def failure_description: ...

        private

        def satisfies_constraint?: ...

        def validate_expectation!: ...

        def validate_subject!: ...
      end
    end
  end
end
