module Domainic
  module Type
    module Constraint
      # A constraint that validates whether an object responds to a specified method
      #
      # This constraint checks if an object implements a particular interface by verifying
      # it responds to a given method name. The method name must be provided as a Symbol.
      #
      # @example
      #   constraint = MethodPresenceConstraint.new(:to_s)
      #   constraint.satisfied_by?(Object.new)  # => true
      #   constraint.satisfied_by?(BasicObject.new)  # => false
      #
      # @author {https://aaronmallen.me Aaron Allen}
      # @since 0.1.0
      class MethodPresenceConstraint
        include Behavior[Symbol, untyped, { }]

        # Get a short description of what this constraint expects
        #
        # @deprecated this method will be removed in version 0.1.0
        #
        # @return [String] description of the expected method
        def short_description: ...

        # Get a short description of why the constraint was violated
        #
        # @deprecated this method will be removed in version 0.1.0
        #
        # @return [String] description of the missing method
        def short_violation_description: ...

        # Coerce the expectation into a symbol
        #
        # @param expectation [Symbol] the method name to check
        #
        # @return [Symbol] coerced method name
        def coerce_expectation: ...

        # Check if the actual value satisfies the constraint
        #
        # @return [Boolean] true if the object responds to the expected method
        def satisfies_constraint?: ...

        # Validate that the expectation is a Symbol
        #
        # @param expectation [Object] the expectation to validate
        #
        # @raise [ArgumentError] if the expectation is not a Symbol
        # @return [void]
        def validate_expectation!: ...
      end
    end
  end
end
