module Domainic
  module Type
    module Constraint
      # @since 0.1.0
      class UniquenessConstraint
        include Behavior

        @expected: nil

        def description: ...

        def failure_description: ...

        private

        def satisfies_constraint?: ...

        def validate_subject!: ...
      end
    end
  end
end
