module Domainic
  module Dev
    class CLI < Thor
      module Command
        # A command to package (build) gem files for the Domainic gems.
        #
        # This class extends {BaseCommand} and includes {Mixin::GemNamesArgument} to provide functionality for
        # packaging gems into `.gem` files in the `pkg` directory.
        #
        # @author {https://aaronmallen.me Aaron Allen}
        # @since 0.1.0
        class PackageGemsCommand < BaseCommand
          include Mixin::GemNamesArgument

          # Execute the gem packaging command.
          #
          # @return [void]
          def execute: () -> void

          private

          # Package a single gem file.
          #
          # @param gem [Gem] the gem to package
          # @return [Boolean] true if packaging was successful
          def package_gem: (Gem) -> bool
        end
      end
    end
  end
end
