module Domainic
  module Command
    module Context
      # @since 0.1.0
      module Behavior
        def self.included: (untyped base) -> untyped

        # @since 0.1.0
        module ClassMethods
          @attributes: AttributeSet

          private

          def attribute: (String | Symbol name, ?(String | Attribute::type_validator)? type_validator_or_description, ?(String | Attribute::type_validator)? description_or_type_validator, ?default: untyped?, ?default_generator: untyped?, ?default_value: untyped?, ?desc: String?, ?description: String?, ?required: bool?, ?type: type_validator?) -> void

          def attributes: () -> AttributeSet

          def inherited: (Class subclass) -> void
        end

        def initialize: (**untyped options) -> void

        def to_hash: () -> Hash[Symbol, untyped]

        alias to_h to_hash
      end
    end
  end
end
