module Domainic
  module Dev
    module Generator
      # A generator for creating new project documentation.
      #
      # This creates new project documentation in the `docs/projects` directory.
      #
      # @author {https://aaronmallen.me Aaron Allen}
      # @since 0.1.0
      class ProjectDocGenerator < BaseGenerator
        @due_date: String

        @status: String

        @start_date: String

        def initialize: (untyped arguments, *untyped options) -> untyped

        # Ensure the project does not already exist.
        #
        # @raise [ArgumentError] if the project already exists
        # @return [void]
        def ensure_project_does_not_exist: () -> void

        # Create the project directory.
        #
        # @return [void]
        def create_project_directory: () -> void

        # Create the project README file.
        #
        # @return [void]
        def create_project_readme: () -> void

        # Print instructions for the user.
        #
        # @return [void]
        def print_instructions: () -> void

        def name: () -> String

        def id: () -> Integer

        private

        attr_reader due_date: String

        attr_reader start_date: String

        attr_reader status: String

        # The name of the project directory based on the project name.
        #
        # @return [String]
        def directory_name: () -> String

        # The color to use for the status badge.
        #
        # @return [String]
        def status_color: () -> String
      end
    end
  end
end
