module Domainic
  module Type
    module Constraint
      class BaseConstraint
        self.@parameters: ParameterSet
        self.@parameter_builder: DSL::ParameterBuilder

        @base: BaseType
        @description: (String | nil)
        @name: Symbol
        @parameters: ParameterSet

        def self.name: () -> String

        def self.parameter: (String | Symbol parameter_name) ? { (DSL::ParameterBuilder) [self: DSL::ParameterBuilder] -> DSL::ParameterBuilder } -> void

        def self.parameters: () -> ParameterSet

        private

        def self.inherited: (singleton(BaseConstraint) subclass) -> void

        def self.parameter_builder: () -> DSL::ParameterBuilder

        public

        attr_reader description: (String | nil)
        attr_reader name: Symbol
        attr_reader parameters: ParameterSet

        def initialize: (BaseType base, ?name: (String | Symbol), ?description: (String | nil), **untyped parameters) -> void

        def validate: (Object subject) -> bool

        private

        def parse_name: (String | Symbol name) -> Symbol
      end
    end
  end
end
