module Domainic
  module Type
    # @since 0.1.0
    module Constraint
      interface _Class
        def new: (Symbol accessor, ?untyped? expectation, ?abort_on_failure: bool) -> Behavior
      end
    end
  end
end
