module Domainic
  module Type
    # @since 0.1.0
    class TypeErrorMessageBuilder
      def self.build: (Behavior type, Behavior::ValidationResult result, untyped value) -> String

      def initialize: (Behavior type, Behavior::ValidationResult result, untyped value) -> void

      def build: () -> String

      private

      def build_constraint_messages: () -> String

      def value_description: () -> String
    end
  end
end
