module Domainic
  module Dev
    class Gem
      # Important {Gem} paths.
      #
      # @since 0.1.0
      class PathSet
        @gemspec: Pathname

        @test: Pathname

        @signature: Pathname

        @root: Pathname

        @library: Pathname

        # @!attribute [r] gemspec
        #   The {Gem}'s gemspec file path.
        #
        #   @return [Pathname] the {Gem}'s gemspec file path.
        attr_reader gemspec: Pathname

        # @!attribute [r] library
        #   The {Gem}'s library directory path.
        #
        #   @return [Pathname] the {Gem}'s library directory path.
        attr_reader library: Pathname

        # @!attribute [r] root
        #   The {Gem}'s root directory path.
        #
        #   @return [Pathname] the {Gem}'s root directory path.
        attr_reader root: Pathname

        # @!attribute [r] signature
        #   The {Gem}'s signature directory path.
        #
        #   @return [Pathname] the {Gem}'s signature directory path.
        attr_reader signature: Pathname

        # @!attribute [r] test
        #   The {Gem}'s test directory path.
        #
        #   @return [Pathname] the {Gem}'s test directory path.
        attr_reader test: Pathname

        # Initialize the a new instance of PathSet.
        #
        # @param root_directory [Pathname] the root directory of the {Gem}.
        # @return [PathSet] the new instance of PathSet.
        def initialize: (Pathname root_directory) -> void
      end
    end
  end
end
