name: Publish wiki
on:
  push:
    branches:
      - main
    paths:
      - docs/**
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Preprocess Links
        run: find . -type f -name "*.md" -exec sed -i '' 's/\](\([^)]*\)\.md)/](\1)/g' {} +
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs/
